/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#f8f9ff",
        "surface-dim": "#cbd5e1",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f8fafc",
        "surface-container": "#f1f5f9",
        "surface-container-high": "#e2e8f0",
        "surface-container-highest": "#cbd5e1",
        "surface-variant": "#e2e8f0",
        "on-surface": "#0f172a",
        "on-surface-variant": "#475569",
        "inverse-surface": "#0f172a",
        "inverse-on-surface": "#f8fafc",
        "outline": "#64748b",
        "outline-variant": "#cbd5e1",
        "surface-tint": "#00685f",
        "primary": "#00685f",
        "on-primary": "#ffffff",
        "primary-container": "#008378",
        "on-primary-container": "#f4fffc",
        "inverse-primary": "#6bd8cb",
        "primary-fixed": "#ccfbf1",
        "primary-fixed-dim": "#99f6e4",
        "on-primary-fixed": "#042f2c",
        "on-primary-fixed-variant": "#115e59",
        "secondary": "#64748b",
        "on-secondary": "#ffffff",
        "secondary-container": "#e2e8f0",
        "on-secondary-container": "#334155",
        "secondary-fixed": "#e2e8f0",
        "secondary-fixed-dim": "#cbd5e1",
        "on-secondary-fixed": "#0f172a",
        "on-secondary-fixed-variant": "#334155",
        "tertiary": "#0284c7",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#0369a1",
        "on-tertiary-container": "#f0f9ff",
        "tertiary-fixed": "#e0f2fe",
        "tertiary-fixed-dim": "#bae6fd",
        "on-tertiary-fixed": "#082f49",
        "on-tertiary-fixed-variant": "#0369a1",
        "error": "#b91c1c",
        "on-error": "#ffffff",
        "error-container": "#fee2e2",
        "on-error-container": "#991b1b",
        background: "#f8f9ff",
        border: {
          DEFAULT: "#e2e8f0",
        },
        text: {
          primary: "#0f172a",
          secondary: "#64748b",
        },
        brand: {
          DEFAULT: "#00685f",
          light: "#f0fdfa",
          border: "#99f6e4",
          hover: "#00564e",
          dark: "#004740",
        },
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.875rem",
        "space-lg": "1.25rem",
        "space-xl": "2rem",
        "margin": "1rem",
        "margin-md": "1.5rem",
        "margin-lg": "2rem",
        "gutter": "1.25rem",
        "gutter-lg": "1.5rem",
      },
      fontFamily: {
        "display": ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
        "headline-lg": ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
        "headline-lg-mobile": ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
        "headline-md": ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
        "headline-sm": ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
        "display-mobile": ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
        "body-lg": ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
        "body-md": ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
        "body-sm": ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
        "label-mono-lg": ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
        "label-mono-md": ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
        "label-mono-sm": ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
        sans: [
          "Inter",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "sans-serif",
        ],
        mono: [
          "JetBrains Mono",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          "monospace",
        ],
      },
      fontSize: {
        "label-mono-sm": ["0.6875rem", { lineHeight: "0.9375rem", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-mono-md": ["0.75rem", { lineHeight: "1.125rem", letterSpacing: "0em", fontWeight: "500" }],
        "label-mono-lg": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-sm": ["0.8125rem", { lineHeight: "1.25rem", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["0.875rem", { lineHeight: "1.375rem", letterSpacing: "0em", fontWeight: "400" }],
        "body-lg": ["1rem", { lineHeight: "1.625rem", letterSpacing: "-0.005em", fontWeight: "400" }],
        "headline-sm": ["1rem", { lineHeight: "1.5rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["1.25rem", { lineHeight: "1.75rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg": ["1.875rem", { lineHeight: "2.375rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["1.5rem", { lineHeight: "2rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display": ["2.75rem", { lineHeight: "3.25rem", letterSpacing: "-0.025em", fontWeight: "700" }],
        "display-mobile": ["2rem", { lineHeight: "2.5rem", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      borderRadius: {
        card: "0.75rem",
        control: "0.5rem",
      },
      maxWidth: {
        content: "1280px",
      },
    },
  },
  plugins: [],
};
